### ISSUE TITLE
How does this compare to proselint?

### ISSUE THREAD

**Issue by Siilwyn** [wooorm/retext-readability#13]
:wave: Hi there this project looks very interesting! Wondering in terms of what it checks, how does it compare to [proselint](https://github.com/amperser/proselint)? With the retext and unified system this certainly seems much more extendible.

**Comment by wooorm** [comment]
Thanks @Siilwyn!

Both are pretty cool, imo, but in my biased view I like retext better.
retext also tries to be smart about things, by using an AST instead of regexes.
The fact that HTML (with [rehype](https://github.com/wooorm/rehype)) and Markdown (with [remark](https://github.com/wooorm/remark)) can be used too, aka [unified](https://unifiedjs.github.io), is very cool.

The pro of prose lint is that it supports a ton of checks. retext doesn’t support so many things. But, in my experience proselint rules can be ported over quite easily, so if you’re missing something you could [create your own plugins](https://unifiedjs.github.io/create-a-plugin.html)!
